import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className }>
        <main className="bg-dark-primary flex flex-col">
          <div className="flex flex-col hero-height  w-max-[1440px]">
            <Navbar />
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
