import type { Metadata } from "next";
// import "@uploadthing/react/styles.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Toaster } from "@/components/ui/toaster";
import NextTopLoader from "nextjs-toploader";
const inter = Inter({ subsets: ["latin"] });
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="bg-dark-primary flex flex-col">
          <div className="flex flex-col hero-height  w-max-[1440px]">
            <NextTopLoader color="#D30427" />
            <Navbar />
            {children}
            <Toaster />
            <Footer />
          </div>
        </main>
      </body>
    </html>
  );
}
